### ISSUE TITLE
Can you explain what is needed to pull a firmware from either a local source or different github?

### ISSUE THREAD

**Issue by earlthesquirrel** [maccoylton/esp-homekit-motion-sensor#10]
Question:

Is it as simple as re-connecting to the device and giving it a different Github path to get different firmware (i.e. a different build that uses a different GPIO pin for motion)?

I note that you have the bin in a particular place... so just wanted to make sure I had things set up correctly.  I'd like to push a binary with some different changes that I would like to make for my particular device.

Thanks for all the assistance so far!

**Comment by earlthesquirrel** [comment]
Forked repo and going to try via that.  Thanks.

**Comment by maccoylton** [comment]
You have two options. 

1) erase and refresh the device as if it were new

2) Assuming you have the latest boot loader, then you can use power cycling to trigger different actions including a factory reset.More explanation here:-  https://github.com/HomeACcessoryKid/life-cycle-manager 

After factory reset the device will restart as an access point. You can connect to that and enter the details of your repository.
