### ISSUE TITLE
Where is Serial Config?

### ISSUE THREAD

**Issue by earlthesquirrel** [maccoylton/esp-homekit-motion-sensor#11]
Where can I see the Serial set up so that I could monitor the ESP when hooked up to USB Serial adapter?   I've grep'ed thru the code and can't seem to find anything anywhere that looks like the configuration for that...

Thanks!

**Comment by maccoylton** [comment]
I use pio to monitor, baud rate is 74880 prior to lashing the bootloader and  15200 afterwards 

```
pio device monitor --port $ESPPORT --baud 115200

pio device monitor --port $ESPPORT --baud 74880
```
