### ISSUE TITLE
Error creating binaries file

### ISSUE THREAD

**Issue by lizzus** [maccoylton/esp-homekit-motion-sensor#3]
One i do "make" i have follow error:
```
firmware/main.bin: No such file or directory
cat: firmware/main.bin: No such file or directory
make: `signature' is up to date.
```
`main.bin.sig` compiled but `main.bin` no

**Comment by maccoylton** [comment]
can you provide more details no your setup please. When you are building make sure you are in the src directory, execute the command make clean and then the make command.

**Comment by maccoylton** [comment]
Assumed resolved as no further feedback, let me know if you still have issues and I can re=open
