### ISSUE TITLE
Onboard led blinking

### ISSUE THREAD

**Issue by Yousefff1** [maccoylton/esp-homekit-motion-sensor#4]
After using vagrant to upload the firmware to the Nodemcu, the nodemcu doesn't show up in my wifi list, and the onboard blue led is blinking.

**Comment by maccoylton** [comment]
I assume you followed the Wiki to install the firmware. Please provide a log file.

**Comment by Yousefff1** [comment]
Hello,

Yes, I have followed the wiki this time, the firmware installed correctly, and I was able to follow all the steps

the onboard led blinks, once every say 30 seconds, and nothing happens
the accessory doesn't show up in the list.

Is it possible to code this to be like esp-homekit-demo ?

Meaning I can build the firmware using vagrant  ?

**Comment by maccoylton** [comment]
>Hello, ...

@Yousefff1 can you provide a log file please 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Yousefff1** [comment]
How would I produce the log file ?

**Comment by maccoylton** [comment]
The firmware should write to the serial port by default.

**Comment by harodev** [comment]
Hello.

I tried to compile locally [not ota, "make test" instead] because for use on the esp-01s I have to use one of the available gpio's [0 or 3] however the device is stuck in a reboot loop and the built in led keeps flashing rapidly, like each time it reboots. 

This is the output:

*** Initial output ***

> `ESP-Open-SDK ver: 0.0.1 compiled @ Jul  5 2019 17:17:16
> phy ver: 273, pp ver: 8.3
> 
> manuf='manuf_unknown' serial='84:0D:8E:model='model_unknown' revision='0.0.0' c#=0
> mode : softAP(86:0d:dc)
> add if1
> bcn 100
> checkWifiTask: status = 255
> HTTP post task starting...
> Suspending http_post_task
> >>> HomeKit: Startinr
> >>> HomeKit: Formatting flash000
> >>> HomeKit: Generated new accessory ID: 86:BE:F0:FC:CE:91
> >>> HomeKit: Generated new accessory key
> >>> mDNS_init: wifi opmode not station
> >>> HomeKit: Configuring mDNS
> rtos assert /home/luis/esp/esp-open-rtos/FreeRTOS/Source/queue.c 1425
> abort() invoked at 0x40204b0b.
> 
> 0x40204b0b: vAssertCalled at /home/luis/esp/esp-open-rtos/FreeRTOS/Source/portable/esp8266/port.c:197
> 
> 
> Stack: SP=0x3fff6360
> 0x3fff6360: 00000000 3fff18d4 00000000 40204b0e
> 
> 0x40204b0e: vAssertCalled at ??:?
> 
> 0x3fff6370: 00000000 3fff63c0 000000e0 40205330
> 
> 0x40205330: xQueueSemaphoreTake at /home/luis/esp/esp-open-rtos/FreeRTOS/Source/queue.c:2364
> 
> 0x3fff6380: 3fff6488 00000001 3ffefe70 402050c4
> 
> 0x402050c4: xQueueGiveMutexRecursive at /home/luis/esp/esp-open-rtos/FreeRTOS/Source/queue.c:2364
> 
> 0x3fff6390: ffffffff 0000000a 3fff1cac 40210950
> 
> 0x40210950: _lock_release_recursive at /home/luis/esp/esp-open-rtos/core/newlib_syscalls.c:202
> 
> 0x3fff63a0: 3fff4450 3fff64d4 3fff1cac 4023b1e0
> 
> 0x4023b1e0: json_flush at ??:?
> 
> 0x3fff63b0: 3fff4450 3fff18d4 4023591c 4021caa9
> 
> 0x4023591c: ungetc at ??:?
> 
> 
> 0x4021caa9: mdns_clear at /home/luis/esp/esp-homekit-motion-sensor/components/esp-homekit/src/mdnsresponder.c:537
> 
> 0x3fff63c0: 3fff63b0 3ffe8978 4023591c 4021bb4f
> 
> 0x4023591c: ungetc at ??:?
> 
> 
> 0x4021bb4f: homekit_mdns_configure_finalize at /home/luis/esp/esp-homekit-motion-sensor/components/esp-homekit/src/port.c:69
> 
> 0x3fff63d0: 00000031 3fff62b4 00000000 4023b1e0
> 
> 0x4023b1e0: json_flush at ??:?
> 
> 
> Free Heap: 34468
> _heap_start 0x3fff2180 brk 0x3fff79ac supervisor sp 0x40000000 sp-brk 34388 bytes
> arena (total_size) 22572 fordblks (free_size) 80 uordblocks (used_size) 22492
> 
> ets Jan  8 2013,rst cause:2, boot mode:(1,5)
> 
> 
> ets Jan  8 2013,rst cause:4, boot mode:(1,5)
> 
> wdt reset

`

Then when I unplug and connect again I get this loop several times each second:

`

> >>> HomeKit: Starting server
> >>> HomeKit: Using existing accessory ID: 86:BE:F0:FC:CE:91
> i opmode not station
> >>> HomeKiguring mDNS
> rtos assert /home/luis/esp/esp-open-rtos/FreeRTOS/Source/queue.c 1425
> abort() invoked at 0x40204b0b.
> 
> Stack: SP=0x3fff6330
> 0x3fff6330: 00000000 3fff18d4 00000000 40204b0e
> 0x3fff6340: 00000000 3fff6390 00000000 40205330
> 0x3fff6350: 3fff6458 00000001 3ffefec0 402050c4
> 0x3fff6360: ffffffff 0000000a 3ff1cac 40210950
> 0x3fff6370: 3ffeeaa0 3fff64a4 3fff1cac 4023b1e0
> 0x3fff6380: 3ffeeaa0 3fff18d4 40c 4021caa9
> 0x3fff6390: 3fff6380 3ffe8978 4023591c 4021bb4f
> 0x3fff63a0: 00000031 3fff6284 00000000 4023b1e0
> 
> Free Heap: 34544
>                 _heap_start 0x3fff2180 brk 0x3fff791c supervisor sp 0x40000000 sp-brk 3453s
> arena (total_size) 22428 fordblks (free_size) 12 uordblocks (used_size) 22416
> 
>  ets Jan  8 2013,rst cause:1, boot mode:(3,6)
> 
> load 0x40100000, len 2292, room 16
> tail 4
> chksum 0x57
> load 0x3ffe8000, len 772, room 4
> tail 0
> chksum 0x0b
> csum 0x0b
> 
> rBoot v1.4.0 - richardaburton@gmail.com
> Flash Size:   8 Mbit
> Flash Mode:   QIO
> Flash Speed:  40 MHz
> rBoot Option: Big flash
> oot Option: RTC data
> 
> Booting rom 0.
> pp_task_hdl : 3ffeff60, prio:14, stack:512
> pm_task_hdl : 3ffef850, prio:1, stack:176
> frc2_timer_task_hdl:0x3fff4300, prio:12, stack:200
> 
> ESP-Open-SDK ver: 0.0.1 compiled @ Jul  5 2019 17:17:16
> phy ver: 273, pp ver: 8.3
> 
> manuf='manuf_unknown' serial='84:0D:8E:97:9A:DC' model='model_unknown' revision='0.0.0' c#0
> mode : softAP(86:0d:8e:97:9a:dc00
> checkWifiTask: status = 255
> HTTP post task starting...
> Suspending http_post_task`

Any ideas?

Thanks!

**Comment by maccoylton** [comment]
Apologies for the slow response, I've been on vacation. Try using the earlier version 37f8a5c6a7d327686a1d04ca81a1faa70f45d02c

**Comment by maccoylton** [comment]
Did the earlier version work?
