### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kerwinf** [maccoylton/esp-homekit-motion-sensor#5]
What pin on a Nodemcu 1.0 12E should the motion sensor trigger pin be connected to? 

I managed to get the firmware installed and working in HomeKit but need to finish the hardware setup. Thank you for the firmware.

There are a few typos in your wiki that you may want to edit.

In the last steps of Stage 1 you have the command to erase the flash duplicated.

In the instructions to connect to WiFi, the GitHub Directory shows "maccoylton/eps-homekit-motion-sensor" and should be "maccoylton/esp-homekit-motion-sensor" noting that "eps" should be "esp"

**Comment by maccoylton** [comment]
Thanks for the feedback , connect to GPIO 12 see the pin numbers here for your device:- https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwi3kdrc-friAhUQJBoKHR_WArIQjRx6BAgBEAU&url=https%3A%2F%2Fwww.instructables.com%2Fid%2FNodeMCU-ESP8266-Details-and-Pinout%2F&psig=AOvVaw2lWSJEvB2e3-hW5mmapr69&ust=1561219425927358
