### ISSUE TITLE
Water Sensor

### ISSUE THREAD

**Issue by lfiocco** [maccoylton/esp-homekit-motion-sensor#6]
How hard would it be to switch this for a water sensor?

**Comment by maccoylton** [comment]
Do you gave a specific water sensor in mind ?

**Comment by lfiocco** [comment]
Sorry, I meant a leak detector sensor. Same type that is used for alarm systems.

**Comment by maccoylton** [comment]
It is possible but I'd need to know the specific make and model you had in mind

**Comment by lfiocco** [comment]
Thanks for reply. I decided to pipe all my water detectors into my alarm system, from there I will zone them and Homebridge will connect it to HomeKit.

Nice project you have here. Well done...

**Comment by maccoylton** [comment]
thanks, lost's on great collaboration going one to enable this

Good luck with yuor solution
