### ISSUE TITLE
Power of then power on, why Home app lost the motion sensor?

### ISSUE THREAD

**Issue by shinyuan** [maccoylton/esp-homekit-motion-sensor#7]
I success write and test it by ESP8266 (NodeMCU),
but whey Power of ESP8266 (NodeMCU) then power on,
why Home app lost the motion sensor?
Thanks for your help and appreciate your amazing hard work.

**Comment by maccoylton** [comment]
Sorry I missed this. Did you get ti working? Please tryout latest version

**Comment by maccoylton** [comment]
No response, assume it's now ok
