### ISSUE TITLE
Changing the GPIO pin

### ISSUE THREAD

**Issue by earlthesquirrel** [maccoylton/esp-homekit-motion-sensor#8]
Question:  I've got some 1btn devices that I'm thinking of converting to motion sensors (they are based on ESP8266mod chips)

I've followed the info in your wiki, got everything flashed,  connected to the device and provided the info that you mentioned (including your git hub directory for the main.bin to load).

However, these boards don't have the GPIO pin you reference in main.c (GPIO 12)
I have access to 15, 2 and 5... that's all that's broken out to the header that I can use)

So, changing the code doesn't seem like a big deal.  But you don't describe the process for how you made the main.bin file.   

Can you provide instructions on that so that I can make the change?

Also, I have a multi-color LED... I might want to update for that later (after this first thing in working... could use RED for motion detected, and different colors for low battery, connected, not connected, OTA occuring, etc.)

Thanks!

Oh, in the wiki -- One editing update -- The line where you describe erasing the ESP, that command is "joined" to the command for flashing.  I think putting it into code format would clean that up (or just split the lines) and make it a little easier for folks to copy/paste.

**Comment by maccoylton** [comment]
If you environment is set right then a simple make command will result in the main.bin file. As per other response I'll post some update code and instruction tomorrow

**Comment by earlthesquirrel** [comment]
Thanks, will close this issue as I've got things co that I can compile and I made the changes to my copy of the code.
