### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by earlthesquirrel** [maccoylton/esp-homekit-motion-sensor#9]
In checking out the release, it's not clear if some things are missing... there isn't an "extras" directory (though it's referenced in the makefile)

You also seem to be referencing openSSL from a fixed location... (that I can easily fix)

Also, which type of ESP chip was the existing main.bin compiled for?
I get what looks like a crash when it tries to start:

dhcp client start...
ip:172.16.147.185,mask:255.255.0.0,gw:172.16.0.1
>>> wifi_config: wifi_config_sta_connect_timeout_callback: Successfully connected
wifiready-done
--- ota_boot...0
OTABOOT VERSION: 0.3.0
--- ota_init
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
active_sector: 0x0
--- ota_set_verify...OFF
--- ota_get_version
--- ota_connect
target IP is 140.82.113.3 bind socket 64417....OK. socket connect to remote....OK. create SSL....OK. set_fd done. SSL to github.com port 443....OK
send request......OK

Fatal exception (28): 
epc1=0x4023f004
epc2=0x00000000
epc3=0x4022dacd
excvaddr=0x00000000
depc=0x00000000
excsave1=0x402186a8
Registers:
a0 402186a8 a1 3fff7be0 a2  00000000 a3  0000000d
a4  00000048 a5  3fff7fe0 a6  00000000 a7  0000004c
a8  3fff7fe0 a9  00000400 a10 0000003b a11 00000000
a12 00000000 a13 00000000 SAR 00000010

Stack: SP=0x3fff7be0
0x3fff7be0: 50545448 312e312f 32303320 756f4620
0x3fff7bf0: 0a0d646e 76726573 203a7265 48746947
0x3fff7c00: 632e6275 0a0d6d6f 65746164 6854203a
0x3fff7c10: 32202c75 614d2031 30322079 32203032
0x3fff7c20: 38353a31 2039333a 0d544d47 6e6f630a
0x3fff7c30: 746e6574 7079742d 74203a65 2f747865
0x3fff7c40: 6c6d7468 6863203b 65737261 74753d74
0x3fff7c50: 0d382d66 6174730a 3a737574 32303320

Free Heap: 30608
_heap_start 0x3fff19d0 brk 0x3fffaaf4 supervisor sp 0x40000000 sp-brk 21772 bytes
arena (total_size) 37156 fordblks (free_size) 8836 uordblocks (used_size) 28320

**Comment by maccoylton** [comment]
The code is somewhat outdated. I'll post a new version tomorrow.

Code is for an ESP8266

you need SDK_PATH defined to compile. Mine is defined as follows:- 

export SDK_PATH=/volumes/case-sensitive/esp-open-rtos

**Comment by earlthesquirrel** [comment]
On my Mac that still doesn't work.

```
ebaugh@Earls-Mac-mini esp-homekit-motion-sensor % printenv SDK_PATH
/Users/ebaugh/Git/esp-open-rtos
`ebaugh@Earls-Mac-mini src % make
/Users/ebaugh/Git/esp-open-rtos/common.mk:223: /Users/ebaugh/Git/esp-homekit-motion-sensor/components/esp-wolfssl/component.mk: No such file or directory
/Users/ebaugh/Git/esp-open-rtos/common.mk:223: /Users/ebaugh/Git/esp-homekit-motion-sensor/components/esp-cjson/component.mk: No such file or directory
/Users/ebaugh/Git/esp-open-rtos/common.mk:223: /Users/ebaugh/Git/esp-homekit-motion-sensor/components/esp-homekit/component.mk: No such file or directory
make: *** No rule to make target `/Users/ebaugh/Git/esp-homekit-motion-sensor/components/esp-homekit/component.mk'.  Stop.
ebaugh@Earls-Mac-mini src %`

Does this path need to end at /bin or just at top of SDK?

**Comment by earlthesquirrel** [comment]
Does it need to be to the bin path?

**Comment by earlthesquirrel** [comment]
Correction in wrong directory...
However here are results:

`ebaugh@Earls-Mac-mini src % make
/Users/ebaugh/Git/esp-open-rtos/common.mk:223: /Users/ebaugh/Git/esp-homekit-motion-sensor/components/esp-wolfssl/component.mk: No such file or directory
/Users/ebaugh/Git/esp-open-rtos/common.mk:223: /Users/ebaugh/Git/esp-homekit-motion-sensor/components/esp-cjson/component.mk: No such file or directory
/Users/ebaugh/Git/esp-open-rtos/common.mk:223: /Users/ebaugh/Git/esp-homekit-motion-sensor/components/esp-homekit/component.mk: No such file or directory
make: *** No rule to make target `/Users/ebaugh/Git/esp-homekit-motion-sensor/components/esp-homekit/component.mk'.  Stop.
ebaugh@Earls-Mac-mini src %`

**Comment by maccoylton** [comment]
As above it should point to the top level of the SDK.

You have not initialised the submodules correctly.

You should do something like:-

git submodule update --init --recursive

**Comment by earlthesquirrel** [comment]
FYI :  Ok, so it's not just path to the  rtos SDK.. there are a fair number of steps to get the rtos SDK installed.  First you have to get the esp-open-sdk installed (I have the normal ESP tools, but this is a different beast, so I had to do this first) 

1) Follow this ticket to get esp-open-sdk installed (at least on Mac ) : https://github.com/pfalcon/esp-open-sdk/issues/342  Esp. note the part of the issue by  phibo23 commented on Mar 14, 2019 near the bottom.  I needed to do all of that to get it built (on a case-sensitive volume)

2) Note that the brew commands (at least for Catalina) doesn't support --with-default-names.
The thread mentioned in #1 seems to be the best way to build.

3) Thanks, didn't realize you had submodules as well (so far, esp-open-rtos and esp-open-sdk do as well).  Anyway, doing that, I am not getting an error that "extras/http-parser/component.mk" is missing.  So that didn't check out, at least so far...  

Thought?

**Comment by maccoylton** [comment]
On point 3 above that suggest I assume you mean you are **now** getting and error on http-parser, which means you still don't have the SDK_PATH set correctly. 

```
echo $SDK_PATH
/volumes/case-sensitive/esp-open-rtos
```

```
ls  $SDK_PATH/extras/http-parser
component.mk	http-parser
```

**Comment by earlthesquirrel** [comment]
Which esp-open-rtos are you working from?
My path is correct : `ebaugh@Earls-Mac-mini extras % echo $SDK_PATH
/Volumes/case-sensitive/esp-open-rtos`

I've verified twice that I have esp-open-rtos checked out recursive..

This one :  
 ```
pfalcon /
esp-open-rtos  
```
does NOT have http-parser 

This one:  
```
SuperHouse /
esp-open-rtos 
```
Does seem to have it.  

I was using the first one, since it seemed to match the esp-open-sdk.  

So, for others, please note the specific path to the package (the 2nd one allows it to compile... of course :-) )

**Comment by earlthesquirrel** [comment]
I'll close this issue now, as with this last update I was able to compile and flash one of the 1btn devices I have that I am trying to make a motion sensor.

**Comment by maccoylton** [comment]
On point 3
>Which esp-open-rtos are you working from? ...

@earlthesquirrel  it’s the SuperHouse one I used 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
